# .github/workflows/deploy.yml
name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install AWS CLI
      run: |
        pip install awscli

    - name: Install Terraform
      run: |
        curl -LO "https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/versions/terraform | jq -r '.[-1].version')/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/versions/terraform | jq -r '.[-1].version')_linux_amd64.zip"
        unzip terraform_*_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform -version  # Verificar la instalación

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Package Lambda function
      run: zip lambda.zip lambda/main.py

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve